language: ruby
install:
- bundle install
script: bundle exec rake site:deploy
sudo: false
env:
  global:
  - secure: A7RoqD30VPubKpCbWOytTUaqq7nnvF4twLdIw7TePG2oCkvyjTRypvsMLg+RtQ68bgnaZK5kZYaUS8kkeiHRVIIzdQOaHXH6c6Md1S9u/lW9kM8+RfRGXscoX9Gm4lNSGzdYJC97qzFuZCjc2Cjz5ueA/oD35zP7lZ5IehfuEUvYfK9xPskXSgAjvf2QmlZpQpJR2vgphlswN2DhKVVUKd1G2JsLiC54tDVx0EFlty27ahItnsy3WE8JG3y8HwkPCylLI0fIe+bT+z86lnzo9ui4dX+xrAxYi53db9LdibwlBpNuwgMn/+OOTx8we5b2jWDaOyHAl6/tCyAozzd93F4pvx2wtnf3PqEEkYFvdqWgR0Qinfyjkwn9tKmyXawbwxaf3WDeqsE7SvIDKn+MSnKD9kSX9RPR1Lz3JfIzw6ZtfWCQ9I+HCbbdgV93lk79x4jDnaKFehZ1Mgoo7nlYZdd63mNjhWqyWoOqqc+hPIz2olLcUZ2CSu+g0YRiLvG2xrzjPZGeZX1D3td2GZglN+h23Wnu2Y5Aqkk9rfDRpq19mloxzMhS4I+4X2+SvuaNh0xLE3OjSK+AuhS0pSpriMAhJClbVZHscmwERW6NI0tgwqaLKO98LQbJp7mQIhMQqjlsYY4ppM5LcgVGX4qe7r3mFAWlvk2SDIMhqwi0gjg=
